---

# Fail for unsupported package managers

- name: Verify presence of a supported package manager
  fail: msg="Failed to find a supported package manager"
  when: ansible_pkg_mgr != 'apt' and ansible_pkg_mgr != 'dnf' and ansible_pkg_mgr != 'pacman'

- name: Inculude package-manager specific settings
  include_tasks: pmngr_{{ ansible_pkg_mgr }}.yml

