---

- name: "[{{ update_level }}] method: security updates ({{ ansible_distribution }}/{{ ansible_pkg_mgr }})."
  zypper: "name=* state=latest update_cache=yes type=patch extra_args='--category security'"
  when: update_level == 'secr'


- name: "[{{ update_level }}] method: safe updates ({{ ansible_distribution }}/{{ ansible_pkg_mgr }})."
  zypper: "name=* state=latest update_cache=yes"
  when: update_level == 'safe'

- name: "[{{ update_level }}] method: not supported, using [safe] instead ({{ ansible_distribution }}/{{ ansible_pkg_mgr }})."
  zypper: "name=* state=latest update_cache=yes"
  when: update_level == 'safe' or update_level == 'deep'

- name: "[{{ update_level }}] method: updating everything ({{ ansible_distribution }}/{{ ansible_pkg_mgr }})."
  zypper: "name=* state=dist-upgrade update_cache=yes extra_args: '--no-allow-vendor-change --allow-arch-change'"
  when: update_level == 'full'
